export interface ILevels {
  [key: number]: string
}

const Levels = {
  1: 'Beginner',
  2: 'Word Warrior',
  3: 'Letter Legend',
  4: 'Alphabet Ace',
  5: 'Scrabble star',
  6: 'Crossword Crusader',
  7: 'Word Wizard',
  8: 'Brain Champion',
  9: 'Puzzle Pro',
  10: 'Letter Genius',
  11: 'Word Master',
  12: 'Alphabet Hero',
  13: 'Word Champion',
  14: 'Crossword King',
  15: 'Scrabble Savant',
  16: 'Letter Boss',
  17: 'Word Winner',
  18: 'Puzzle Pal',
  19: 'Alphabet Adept',
  20: 'Crossword Connoisseur',
  21: 'Word Ace',
  22: 'Letter Champion',
  23: 'Word Whisperer',
  24: 'Puzzle Royal',
  25: 'Scrabble Supreme',
  26: 'Crossword Champion',
  27: 'Word Weaver',
  28: 'Alpha Bet',
  29: 'Spellbound',
  30: 'Letter Ladder',
  31: 'Wordplay',
  32: 'Vocab Venture',
  33: 'Brain Booster',
  34: 'Linguistic League',
  35: 'Lexicon League',
  36: 'Verbal Victory',
  37: 'Language Labyrinth',
  38: 'Word Wiz',
  39: 'Alphabet Alley',
  40: 'Mind Meld',
  41: 'Spelling Sprint',
  42: 'Letter Lock',
  43: 'Word Wangle',
  44: 'Vocab Voyage',
  45: 'Dictionary Dash',
  46: 'Syntax Shuffle',
  47: 'Linguistic Lunge',
  48: 'Lexical Lasso',
  49: 'Word War',
  50: 'Grammar Games',
  51: 'Alphabet Assault',
  52: 'Mind Mania',
  53: 'Spelling Showdown',
  54: 'Letter Leap',
  55: 'Word Whizzing',
  56: 'Vocab Vault',
  57: 'Dictionary Duel',
  58: 'Syntax Saga',
  59: 'Linguistic Lineup',
  60: 'Lexical Limelight',
  61: 'Word Wrestling',
  62: 'Grammar Genius',
  63: 'Alphabet Adventure',
  64: 'Mind Marathon',
  65: 'Spelling Spectacle',
  66: 'Letter Launch',
  67: 'Word Wonder',
  68: 'Vocab Vortex',
  69: 'Dictionary Duelist',
  70: 'Syntax Scramble',
  71: 'Linguistic Labyrinth',
  72: 'Lexical Legend',
  73: 'Grammar Guru',
  74: 'Alphabet Acrobatics',
  75: 'Mind Mastery',
  76: 'Spelling Smackdown',
  77: 'Letter Lift',
  78: 'Word Whirlwind',
  79: 'Vowel Victory',
  80: 'Word Warp',
  81: 'Alpha Achiever',
  82: 'Spelling Savant',
  83: 'Letter Labyrinth',
  84: 'Word Whiz Kid',
  85: 'Puzzle Perfection',
  86: 'Vocab Vandal',
  87: 'Brain Busting Battle',
  88: 'Linguistic Laser',
  89: 'Word Wanderlust',
  90: 'Lexicon Liberator',
  91: 'Letter Lockdown',
  92: 'Verbal Volley',
  93: 'Language Legend',
  94: 'Mind Meltdown',
  95: 'Spelling Sensation',
  96: 'Royal Word Wizard',
  97: 'Queen of Words',
  98: 'Champion of LetterLink',
  99: 'King of LetterLink',
  100: 'LetterLink Legend',
}

export default Levels
