export interface IProfileIcon {
  [key: string]: string
}

const ProfileIcons = {
  Bat: '/profileIcons/bat.svg',
  Bear: '/profileIcons/bear.svg',
  Bee: '/profileIcons/bee.svg',
  Buffalo: '/profileIcons/buffalo.svg',
  Butterfly: '/profileIcons/butterfly.svg',
  Chameleon: '/profileIcons/chameleon.svg',
  Chicken: '/profileIcons/chicken.svg',
  Cow: '/profileIcons/cow.svg',
  Dog: '/profileIcons/dog.svg',
  Duck: '/profileIcons/duck.svg',
  Eagle: '/profileIcons/eagle.svg',
  Elephant: '/profileIcons/elephant.svg',
  Fox: '/profileIcons/fox.svg',
  Frog: '/profileIcons/frog.svg',
  Giraffe: '/profileIcons/giraffe.svg',
  Goat: '/profileIcons/goat.svg',
  Hippo: '/profileIcons/hippo.svg',
  Horse: '/profileIcons/horse.svg',
  Kangaroo: '/profileIcons/kangaroo.svg',
  Koala: '/profileIcons/koala.svg',
  Ladybug: '/profileIcons/ladybug.svg',
  Lemur: '/profileIcons/lemur.svg',
  Lion: '/profileIcons/lion.svg',
  Monkey: '/profileIcons/monkey.svg',
  Owl: '/profileIcons/owl.svg',
  Panda: '/profileIcons/panda.svg',
  Penguin: '/profileIcons/penguin.svg',
  Pig: '/profileIcons/pig.svg',
  Rabbit: '/profileIcons/rabbit.svg',
  Raccoon: '/profileIcons/raccoon.svg',
  Rhino: '/profileIcons/rhino.svg',
  Shark: '/profileIcons/shark.svg',
  Sheep: '/profileIcons/sheep.svg',
  Snake: '/profileIcons/snake.svg',
  Swan: '/profileIcons/swan.svg',
  Tiger: '/profileIcons/tiger.svg',
  Walrus: '/profileIcons/walrus.svg',
  Whale: '/profileIcons/whale.svg',
  Wolf: '/profileIcons/wolf.svg',
  Zebra: '/profileIcons/zebra.svg',
  Unknown: 'profileIcons/unknown.svg',
  Cat: 'profileIcons/cat.svg',
  Sloth: 'profileIcons/sloth.svg',
  Squirrel: 'profileIcons/squirrel.svg',
  Cheetah: 'profileIcons/cheetah.svg',
  Ostrich: 'profileIcons/ostrich.svg',
  Wildboar: 'profileIcons/wildboar.svg',
  Donkey: 'profileIcons/donkey.svg',
  Deer: 'profileIcons/deer.svg',
  Hamster: 'profileIcons/hamster.svg',
  Beetle: 'profileIcons/beetle.svg',
}

export default ProfileIcons
